"use client";

import Link from "next/link";
import { ChangeEvent, useEffect, useState } from "react";

const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
type Course = { id: number; title: string; code: string };
type Exam = { id: number; title: string };
type Progress = { question_count: number; uploaded_count: number; finalized_count: number; questions: { question_id: number; question_number: number; prompt: string; maximum_marks: number; uploaded_count: number; ocr_ready_count: number; reviewed_count: number; suggested_count: number; finalized_count: number }[] };
async function api<T>(path: string): Promise<T> { const response = await fetch(`${apiUrl}${path}`, { credentials: "include" }); if (!response.ok) throw new Error("Could not load progress."); return response.json() as Promise<T>; }

export default function DashboardPage() {
  const [courses, setCourses] = useState<Course[]>([]); const [exams, setExams] = useState<Exam[]>([]); const [courseId, setCourseId] = useState(""); const [examId, setExamId] = useState(""); const [progress, setProgress] = useState<Progress | null>(null); const [notice, setNotice] = useState("Choose an exam to see its marking progress.");
  useEffect(() => { api<Course[]>("/api/courses").then(setCourses).catch((error) => setNotice(error.message)); }, []);
  async function selectCourse(event: ChangeEvent<HTMLSelectElement>) { const value = event.target.value; setCourseId(value); setExamId(""); setExams([]); setProgress(null); if (!value) return; try { setExams(await api<Exam[]>(`/api/courses/${value}/exams`)); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not load exams."); } }
  async function selectExam(event: ChangeEvent<HTMLSelectElement>) { const value = event.target.value; setExamId(value); setProgress(null); if (!value) return; try { const loaded = await api<Progress>(`/api/exams/${value}/progress`); setProgress(loaded); setNotice(loaded.uploaded_count ? "Continue from the next status in each question row." : "This exam has no uploaded answers yet."); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not load progress."); } }
  return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-100"><div className="mx-auto max-w-6xl"><Link href="/" className="text-sm font-semibold text-cyan-400">← RubriCheck AI</Link><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-bold">Exam review dashboard</h1><p className="mt-2 text-slate-400">Track each answer batch through OCR, review, and finalization.</p></div><Link href="/submissions" className="rounded-lg border border-slate-700 px-4 py-2 text-sm font-semibold">Open review queue</Link></div><p className="mt-6 rounded-lg border border-cyan-400/25 bg-cyan-400/10 px-4 py-3 text-sm text-cyan-100">{notice}</p><section className="mt-6 rounded-xl border border-slate-800 bg-slate-900 p-6"><div className="grid gap-3 md:grid-cols-2"><select value={courseId} onChange={selectCourse} className="field"><option value="">Select course</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.code} — {course.title}</option>)}</select><select value={examId} onChange={selectExam} disabled={!courseId} className="field"><option value="">Select exam</option>{exams.map((exam) => <option key={exam.id} value={exam.id}>{exam.title}</option>)}</select></div></section>{progress && <><section className="mt-6 grid gap-4 md:grid-cols-3">{[["Questions", progress.question_count], ["Uploaded answers", progress.uploaded_count], ["Finalized", progress.finalized_count]].map(([label, count]) => <div key={String(label)} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-1 text-3xl font-bold text-cyan-300">{count}</p></div>)}</section><section className="mt-6 overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-800 bg-slate-950 text-slate-400"><tr><th className="px-5 py-3">Question</th><th className="px-5 py-3">Uploaded</th><th className="px-5 py-3">OCR</th><th className="px-5 py-3">Reviewed</th><th className="px-5 py-3">Suggested</th><th className="px-5 py-3">Finalized</th></tr></thead><tbody>{progress.questions.map((question) => <tr key={question.question_id} className="border-b border-slate-800 last:border-0"><td className="px-5 py-4"><p className="font-semibold">Q{question.question_number} · {question.maximum_marks} marks</p><p className="max-w-md truncate text-slate-400" title={question.prompt}>{question.prompt}</p></td><td className="px-5 py-4">{question.uploaded_count}</td><td className="px-5 py-4">{question.ocr_ready_count}</td><td className="px-5 py-4">{question.reviewed_count}</td><td className="px-5 py-4">{question.suggested_count}</td><td className="px-5 py-4 font-semibold text-cyan-300">{question.finalized_count}</td></tr>)}</tbody></table></div></section></>}</div></main>;
}
